server:
  port: 8088

spring:
  application:
    name: fraud-service

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:secret}
      timeout: 2000ms

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    com.bankapp: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    redis:
      host: redis
  kafka:
    bootstrap-servers: kafka:29092
