server:
  port: 8083

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/transaction_db
    username: ${DB_USERNAME:bankapp}
    password: ${DB_PASSWORD:secret}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:secret}
      timeout: 2000ms

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

fraud-service:
  url: ${FRAUD_SERVICE_URL:http://localhost:8088}

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    com.bankapp: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/transaction_db
  data:
    redis:
      host: redis
  kafka:
    bootstrap-servers: kafka:29092

fraud-service:
  url: http://fraud-service:8088

user-service:
  url: http://user-service:8081
